version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
    environment:
      JAVA_OPTS: "-Duser.timezone=Europe/Paris"
    restart: always

volumes:
  jenkins-data: