name: Travis CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Travis CI build
      uses: travis-ci/travis-ci-action@v1
      with:
        token: lWCEJ2m5Ga7UB5GPEsQquA
        repository-slug: ${{ github.repository }}
        job-id: id_of_the_travis_job
